---
- name: Install Apache2
  hosts: all

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Apache2 Install
      apt:
        name: apache2
        state: present

    - name: Start Apache2
      service:
        name: apache2
        state: started

    - name: Enable Apache2
      service:
        name: apache2
        enabled: yes
