---
- name: Cleanup old log files and unused kernels
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Find all files in /var/log older than 7 days
      find:
        paths: /var/log
        age: 7d
        recurse: yes
      register: filesOlderThan7

    - name: Remove old log files
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ filesOlderThan7.files }}"

    - name: Purge unused kernels and packages (Ubuntu only)
      command: apt-get autoremove --purge -y
      ignore_errors: true
