---
- name: Set passwordless sudo for patchman
  hosts: all
  become: true
  tasks:

    - name: Create sudoers file for patchman
      copy:
        dest: /etc/sudoers.d/patchman
        content: "patchman ALL=(ALL) NOPASSWD: ALL\n"
        owner: root
        group: root
        mode: '0440'
        validate: '/usr/sbin/visudo -cf %s'
